run_name: WikiDiverse
seed: 43
pretrained_model: 'clip-vit-base-patch32'
lr: 1e-5


data:
  num_entity: 132460
  kb_img_folder: /data/WikiDiverse/kb_image
  mention_img_folder: /data/WikiDiverse/mention_images
  qid2id: /data/WikiDiverse/qid2id.json
  entity: /data/WikiDiverse/kb_entity.json
  train_file: /data/WikiDiverse/WikiDiverse_train.json
  dev_file: /data/WikiDiverse/WikiDiverse_dev.json
  test_file: /data/WikiDiverse/WikiDiverse_test.json
  batch_size: 64
  num_workers: 8
  text_max_length: 50
  visual_patch_length: 50
  eval_chunk_size: 1000
  eval_batch_size: 50
  embed_update_batch_size: 512

  n: 16
  num_candidates: 16
  llm: 'deepseek-v3'


model:
  input_hidden_dim: 512
  input_image_hidden_dim: 768
  hidden_dim: 512
  hidden_size: 512
  num_hidden_layers: 1
  num_attention_heads: 2
  use_intermediate: 0
  intermediate_size: 512
  target_scale: 10
  modal_num: 2
  temperature: 1.0
  router_weight: 0.01
  router_temperature_modal: 1.0
  router_temperature_grain: 1.0


trainer:
  accelerator: 'gpu'
  devices: 1
  max_epochs: 20
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 2
  log_every_n_steps: 30